import { FileDiff, PRContext } from '../types';

export function buildReviewPrompt(files: FileDiff[], context: PRContext): string {
  const filesContent = files.map(file => `
--- FILE: ${file.filename} ---
Status: ${file.status}
Additions: ${file.additions}, Deletions: ${file.deletions}

${file.patch}
`).join('\\n');

  return `You are an expert code reviewer. Analyze the following pull request changes and identify issues.

PR Context:
- Repository: ${context.owner}/${context.repo}
- PR #${context.pullNumber}: ${context.title}
- Author: ${context.author}
- Base Branch: ${context.baseBranch}
- Head Branch: ${context.headBranch}
- Description: ${context.description || 'No description provided'}

Changed Files:
${filesContent}

Analyze the code for these categories:
1. SECURITY: SQL injection, XSS, hardcoded secrets, unsafe deserialization, path traversal, insecure auth
2. PERFORMANCE: N+1 queries, memory leaks, inefficient algorithms, unnecessary computations, large object creation
3. CODE QUALITY: Dead code, excessive complexity, magic numbers, poor naming, missing error handling, code duplication
4. DESIGN: Anti-patterns, tight coupling, missing abstractions, breaking SOLID principles, API design issues

Return ONLY valid JSON in this exact format (no markdown, no explanation):
{
  "issues": [
    {
      "file": "filename.ext",
      "line": 42,
      "severity": "critical|high|medium|low",
      "category": "security|performance|quality|design",
      "title": "Brief issue title",
      "description": "Detailed explanation of the issue",
      "suggestion": "Specific code suggestion to fix"
    }
  ],
  "summary": "Overall assessment of the PR (2-3 sentences)",
  "stats": {
    "critical": 0,
    "high": 0,
    "medium": 0,
    "low": 0,
    "total": 0
  }
}

Rules:
- Be precise with line numbers from the diff
- Only flag real issues, avoid false positives
- Provide actionable, specific suggestions
- If no issues found, return empty issues array
- Severity guide: critical = security vuln or crash, high = significant bug, medium = maintainability issue, low = style/nitpick
- Focus on the CHANGED code, not existing code in the file`;
}

export function buildCommentBody(result: { issues: any[]; summary: string; stats: any }): string {
  const { issues, summary, stats } = result;

  if (issues.length === 0) {
    return `## ✅ AI Code Review Complete

${summary}

No issues found in this PR. Great work! 🎉`;
  }

  const severityEmojis = {
    critical: '🔴',
    high: '🟠',
    medium: '🟡',
    low: '🔵'
  };

  const severityLabels = {
    critical: 'Critical',
    high: 'High',
    medium: 'Medium',
    low: 'Low'
  };

  // Group issues by severity
  const grouped = issues.reduce((acc, issue) => {
    acc[issue.severity] = acc[issue.severity] || [];
    acc[issue.severity].push(issue);
    return acc;
  }, {} as Record<string, typeof issues>);

  const order: (keyof typeof severityEmojis)[] = ['critical', 'high', 'medium', 'low'];

  let body = `## 🤖 AI Code Review Complete

${summary}

### Summary
| Severity | Count |
|----------|-------|
| 🔴 Critical | ${stats.critical} |
| 🟠 High | ${stats.high} |
| 🟡 Medium | ${stats.medium} |
| 🔵 Low | ${stats.low} |
| **Total** | **${stats.total}** |

---

`;

  for (const severity of order) {
    const group = grouped[severity];
    if (!group || group.length === 0) continue;

    body += `### ${severityEmojis[severity]} ${severityLabels[severity]} Issues (${group.length})

`;

    for (const issue of group) {
      body += `**${issue.title}**
`;
      body += `- **File:** \`${issue.file}:${issue.line}\`
`;
      body += `- **Category:** ${issue.category}
`;
      body += `- **Description:** ${issue.description}
`;
      body += `- **Suggestion:** ${issue.suggestion}

`;
    }
  }

  body += `---
*This review was generated by AI Code Review Agent. Please verify all suggestions before applying.*`;

  return body;
}
